[package]
name = "dodrio"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
bumpalo = "1.0.2"
wasm-bindgen = "0.2.25"
js-sys = "0.3.2"

[dependencies.web-sys]
version = "0.3.2"
features = [
  "Document",
  "Element",
  "Node",
  "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[workspace]
members = [
  "./example/rust"
]
