[package]
name = "dodrio"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
bumpalo = "2.1.0"
futures = "0.1.25"
wasm-bindgen = "0.2.34"
wasm-bindgen-futures = "0.3.11"
js-sys = "0.3.11"
log = "0.4.6"

[dependencies.web-sys]
version = "0.3.11"
features = [
  "console",
  "Document",
  "Element",
  "Event",
  "Node",
  "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.2.34"
console_log = "0.1.2"

[dev-dependencies.web-sys]
version = "0.3.11"
features = [
  "Attr",
  "EventTarget",
  "HtmlElement",
  "NamedNodeMap",
  "NodeList",
]

[profile.release]
incremental = false
lto = true
opt-level = "s"

[workspace]
members = [
  "./examples/counter",
  "./examples/hello-world",
  "./examples/input-form",
  "./examples/todomvc",
]
