[package]
name = "dodrio"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
bumpalo = "1.0.2"
wasm-bindgen = "0.2.25"
js-sys = "0.3.2"
log = "0.4.6"

[dependencies.web-sys]
version = "0.3.8"
features = [
  "console",
  "Document",
  "Element",
  "Node",
  "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.2"
console_log = "0.1.2"

[dev-dependencies.web-sys]
version = "0.3.8"
features = [
  "Attr",
  "NamedNodeMap",
  "NodeList",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[workspace]
members = [
  "./examples/counter/crate",
  "./examples/hello-world/crate",
  "./examples/input-form/crate",
]

[patch.crates-io]
bumpalo = { path = "../bumpalo" }
console_error_panic_hook = { path = "../console_error_panic_hook" }
wasm-bindgen = { path = "../wasm-bindgen" }
wasm-bindgen-test = { path = "../wasm-bindgen/crates/test" }
js-sys = { path = "../wasm-bindgen/crates/js-sys" }
web-sys = { path = "../wasm-bindgen/crates/web-sys" }
