[package]
name = "compile-tests"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
publish = false

[dependencies]
dodrio = { path = ".." }

[dev-dependencies]
compiletest_rs = "0.3.18"
